---
title: "Network Graph of shared files"
author: "Dave Hurst"
output:
  html_notebook: default
  html_document:
    keep_md: yes
---

The libraries we'll use (still a little extraneous stuff here to clean up)

```{r libs, message=FALSE, warning=FALSE}
library(tidyverse)
library(stringr)
library(googledrive)
library(googlesheets)
library(lubridate)
library(data.tree)
library(cowplot)
library(tictoc)
theme_set(theme_gray())

# library(network)
# library(sna)
#library(GGally)
library(networkD3)
library(randomNames) 
library(igraph)
library(visNetwork)
```

Use a cached file for the interactive demo

```{r get_files}
cached = TRUE
if (! exists('cache_all')) cache_all <- 'all_dhurst79graph.rds'
if (file.exists(cache_all) && cached) {
    files <- readRDS(cache_all)
} else {
    tic()
    files <- drive_find()
    saveRDS(files, cache_all)
    toc()
}
```

Let's look at both count and size accumulation over time. Note that file size is only counted for files that are stored in native format (i.e. not Google Docs)

```{r data_prep}
files <- files %>% mutate(shared = map_lgl(drive_resource, 'shared'))

drive_auth()
me <- drive_user()$emailAddress
shared <- files %>% filter(shared)

#shrink things down for the interactive demo
#shared_orig <- shared 
max_net <- min(200, nrow(shared))
shared <- shared[1:max_net, ]

scale_width <- function(x, z = 10) { 
    x0 <- x - min(x)
    xz <- x0 * (z - 1) / max(x0)
    zz <- xz + 1
}
```
```{r loops}
share_with_df <- tibble()
for (i in 1:nrow(shared)) { ## need to purrrfect this
    #for (i in 1:17) {
    xx <- shared[i, ]$drive_resource[[1]]$permissions
    if(is.null(xx)) next  # gap? Files shared with anyone not added to my Drive
    owner <- shared[i, ]$drive_resource[[1]]$owners[[1]]$emailAddress 
    for (j in 1:length(xx)) {
        if (xx[[j]]$role == 'owner') next
        ptype <- xx[[j]]$type
        sharee <- ifelse(ptype == 'user', xx[[j]]$emailAddress, ptype)  # {name} or 'anyone'
        if (sharee == me) ptype = 'me'
        share_with_df <- bind_rows(share_with_df,
                                   tibble(from = owner, to = sharee, group = ptype, arrows = 'to' ))
    } 
    if (i %% 250 == 0) print(i)
}
nodes <- tibble( id = c(share_with_df$to, share_with_df$from) %>% unique()) %>%
    mutate( title = str_replace(id, "@.*", ""),
            group = str_replace(id, ".*@", ""),
            shape = case_when(id == me ~ 'diamond', id == 'anyone' ~ 'square', TRUE ~ 'circle'))
            #label = ifelse(id == me, 'me', ''))

#group counts
domain_count <- nodes %>% count(group) %>% arrange(desc(n))
keep <- domain_count$group %>% head(5) %>% c('anyone')

nodes <- nodes %>%
    mutate(group = ifelse(group %in% keep, group, 'other'))

edges <- share_with_df %>%
    group_by(from, to, group, arrows) %>%
    summarise(width = n()) %>% ungroup %>%
    mutate(width = scale_width(width, z = 20)) 
vn <- visNetwork(nodes, edges)
vn %>% visLegend()
```

```{r}
process_files <- function(i) {
    xx <- shared[i, ]$drive_resource[[1]]$permissions
    #if(is.null(xx)) {return (tibble(from = NA, to = NA, group = NA, arrows = NA ))}
    owner <- shared[i, ]$drive_resource[[1]]$owners[[1]]$emailAddress 
    map_dfr(seq_along(xx), gather_pals, xx = xx, owner = owner)
}

gather_pals <- function(xx, j, owner) {
    if (xx[[j]]$role == 'owner') {return (tibble(from = NA, to = NA, group = NA, arrows = NA ))}
    ptype <- xx[[j]]$type
    sharee <- ifelse(ptype == 'user', xx[[j]]$emailAddress, ptype)  # {name} or 'anyone'
    if (sharee == me) ptype = 'me'
    tibble(from = owner, to = sharee, group = ptype, arrows = 'to' )
}


share_with_df <- map_dfr(seq_len(nrow(shared)), process_files) 

nodes <- tibble( id = c(share_with_df$to, share_with_df$from) %>% unique()) %>%
    mutate( title = str_replace(id, "@.*", ""),
            group = str_replace(id, ".*@", ""),
            shape = case_when(id == me ~ 'diamond', id == 'anyone' ~ 'square', TRUE ~ 'circle'))
            #label = ifelse(id == me, 'me', ''))

#group counts
domain_count <- nodes %>% count(group) %>% arrange(desc(n))
keep <- domain_count$group %>% head(5) %>% c('anyone')

nodes <- nodes %>%
    mutate(group = ifelse(group %in% keep, group, 'other'))

edges <- share_with_df %>%
    group_by(from, to, group, arrows) %>%
    summarise(width = n()) %>% ungroup %>%
    mutate(width = scale_width(width, z = 20)) 
vn <- visNetwork(nodes, edges)
vn %>% visLegend()
```

