---
title: "Analysis of my Google Drive files (WIP)"
author: "Dave Hurst"
output:
  html_notebook: default
  html_document:
    keep_md: yes
---


```{r libs, message=FALSE, warning=FALSE}
library(tidyverse)
library(stringr)
library(googledrive)
library(googlesheets)
library(lubridate)
library(data.tree)
library(cowplot)
library(tictoc)
theme_set(theme_gray())

# library(network)
# library(sna)
#library(GGally)
library(networkD3)
library(randomNames) 
library(igraph)
library(visNetwork)
```

```{r get_files}
cached = TRUE
if (! exists('cache_all')) cache_all <- 'all.rds'
if (file.exists(cache_all) && cached) {
    files <- readRDS(cache_all)
} else {
    tic()
    files <- drive_find()
    saveRDS(files, cache_all)
    toc()
}
```

Let's look at both count and size accumulation over time. Note that file size is only counted for files that are stored in native format (i.e. not Google Docs)

```{r plot_time}
files <- files %>% googledrive:::promote('createdTime')
files <- files %>% googledrive:::promote('shared')
files <- files %>% googledrive:::promote('ownedByMe')
files <- files %>% drive_reveal(what = 'mime_type') 

n_shared <- sum(files$shared) 
drive_auth()
me <- drive_user()$emailAddress
shared <- files %>% filter(shared)

# there are only one 'owners' per file
# proof: purrr::map_int(files$drive_resource, function(.x) length(.x$owners)) %>% sum() == nrow(files)
pals <- rep(NA, nrow(shared))
dnet <- graph.empty(n = 1, directed = TRUE)
V(dnet)$name <- me

for (i in 1:nrow(shared)) { ## need to purrrfect this
#for (i in 1:17) {
    xx <- shared[i, ]$drive_resource[[1]]$permissions
    pals[i] <- purrr::map_chr(xx, function(.x) #.x$type) %>% paste(collapse = ',')
        ifelse(.x$type == 'user', .x$emailAddress, .x$type)) %>% setdiff(me) %>% paste(collapse = ',')
    all_names <- str_split(pals[i], ',') %>% unlist()
    if (length(all_names) == 1 && str_length(all_names) == 0) next # special case: file shared not write
    new_names <- setdiff( all_names, V(dnet)$name)
    if (length(new_names) == 0) next # special case: we know all these guys already
    for(newv in new_names) dnet <- dnet + newv
    owner <- shared[i, ]$drive_resource[[1]]$owners[[1]]$emailAddress
    shared_with <- setdiff( c(me, all_names), owner)
    shares <- rep(owner, length(shared_with) * 2); shares[seq(2, length(shared_with) * 2, 2)] <- shared_with #has to be a more elegant way
    dnet <- igraph::add.edges(dnet, shares)
}
```
```{r}
com <- cluster_spinglass(dnet, spins=5)
V(dnet)$color <- com$membership+1

ix_me <- grep(me, V(dnet)$name)
ix_anyone <- grep('^anyone$', V(dnet)$name)

V(dnet)$name[ix_me] <- 'me'

V(dnet)$color[ix_me] <- 'yellow'
V(dnet)$color[ix_anyone] <- 'black'

# v_size <- 3
# V(dnet)$size <- v_size
# V(dnet)$size[ix_me] <- v_size * 2

V(dnet)$shape <- 'circle'
V(dnet)$shape[c(ix_me, ix_anyone)] <- 'square'

deg <- degree(dnet, mode="all")
V(dnet)$size <- log(deg+3) * 2
plot(dnet, vertex.label=NA, edge.arrow.size = 0.2, curved=TRUE)
```

```{r}
#shared_orig <- shared
#shared <- shared [1:20, ]

share_with_df <- tibble()
for (i in 1:nrow(shared)) { ## need to purrrfect this
    #for (i in 1:17) {
    xx <- shared[i, ]$drive_resource[[1]]$permissions
    if(is.null(xx)) next  # gap? Files shared with anyone not added to my Drive
    owner <- shared[i, ]$drive_resource[[1]]$owners[[1]]$emailAddress 
    for (j in 1:length(xx)) {
        sprintf("type = %s\n", xx[[j]]$type)
        if (xx[[j]]$role == 'owner') next
        ptype <- xx[[j]]$type
        sharee <- ifelse(ptype == 'user', xx[[j]]$emailAddress, ptype)  # {name} or 'anyone'
        if (sharee == me) ptype = 'me'
        share_with_df <- bind_rows(share_with_df,
                                   tibble(from = owner, to = sharee, group = ptype, arrows = 'to' ))
    } 
    
}
nodes <- tibble( id = c(share_with_df$to, share_with_df$from) %>% unique()) %>%
    mutate( title = str_replace(id, "@.*", ""),
            group = str_replace(id, ".*@", ""),
            shape = case_when(id == me ~ 'diamond', id == 'anyone' ~ 'square', TRUE ~ 'circle'))
            #label = ifelse(id == me, 'me', ''))

#group counts
domain_count <- nodes %>% count(group) %>% arrange(desc(n))
keep <- domain_count$group %>% head(5) %>% c('anyone')

scale_width <- function(x, z = 10) { 
    x0 <- x - min(x)
    xz <- x0 * (z - 1) / max(x0)
    zz <- xz + 1
}
nodes <- nodes %>%
    mutate(group = ifelse(group %in% keep, group, 'other'))

edges <- share_with_df %>%
    group_by(from, to, group, arrows) %>%
    summarise(width = n()) %>% ungroup %>%
    mutate(width = scale_width(width, z = 20)) 
swu <- unique(share_with_df)
vn <- visNetwork(nodes, edges)
vn %>% visLegend()
```

